CREATE TABLE IF NOT EXISTS presets (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  target REAL NOT NULL,
  tolerance REAL NOT NULL,
  is_mono_check BOOLEAN NOT NULL DEFAULT FALSE,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_by TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
